spring:
  liquibase:
    change-log: classpath:/path/to/changelog/db.changelog-master.xml
    enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: none

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host}:${port}/${db_name}
    username: ${username}
    password: ${password}

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: ${path}